# Generated by Django 3.1.6 on 2021-02-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddtastForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=100)),
                ('Task', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('Deadline', models.DateField()),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('C', 'Complete'), ('P', 'Panding'), ('R', 'Running')], max_length=1)),
            ],
        ),
    ]
