# Generated by Django 3.1.6 on 2021-02-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddtastForm',
            new_name='AddtaskForm',
        ),
    ]
