# Generated by Django 3.1.6 on 2021-02-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210222_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtaskform',
            name='Status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Panding', 'Panding'), ('Running', 'Running')], max_length=10),
        ),
    ]
